/*
 * Principal.java
 *
 * Esse projeto é só um esqueleto para ilustrar os conceitos de Herança e 
 * Polimorfismo.
 * 
 * Será necessário criar mais classes para representar:
 * - Cavaleiro e Arqueiro
 * 
 * Será necessário pensar em uma forma para organizar todos os personagens em
 * uma única ArrayList
 * 
 * Será necessário pensar em uma forma para permitir 'mover' ou 'atacar'
 * todos os personagens, somente aldeões, somente arqueiros ou somente cavaleiros.
 * 
 * Pensar em uma solução com Classe Abstrata ou Interfaces
 * 
 * Created on 06/10/2011, 16:22:51
 */
package poo;

import java.util.Random;

/**
 *
 * http://docente.ifsc.edu.br/mello
 */
public class Principal extends javax.swing.JFrame {

   private Random sorteio;

   /** Creates new form Principal */
   public Principal() {
      initComponents();
      this.setLocationRelativeTo(null);
      this.sorteio = new Random();
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      buttonGroup1 = new javax.swing.ButtonGroup();
      jPTela = new Tela(this);
      jPLateral = new javax.swing.JPanel();
      jPMovimentar = new javax.swing.JPanel();
      jRBAldeao = new javax.swing.JRadioButton();
      jRBArqueiro = new javax.swing.JRadioButton();
      jRBCavaleiro = new javax.swing.JRadioButton();
      jRBTodos = new javax.swing.JRadioButton();
      jBCima = new javax.swing.JButton();
      jBEsquerda = new javax.swing.JButton();
      jBBaixo = new javax.swing.JButton();
      jBDireita = new javax.swing.JButton();
      jBCima1 = new javax.swing.JButton();
      jPCriar = new javax.swing.JPanel();
      jBAldeao = new javax.swing.JButton();
      jBCavaleiro = new javax.swing.JButton();
      jBArqueiro = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("J2D - Conceitos de Herança e Polimorfismo");
      setResizable(false);

      javax.swing.GroupLayout jPTelaLayout = new javax.swing.GroupLayout(jPTela);
      jPTela.setLayout(jPTelaLayout);
      jPTelaLayout.setHorizontalGroup(
         jPTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 466, Short.MAX_VALUE)
      );
      jPTelaLayout.setVerticalGroup(
         jPTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 420, Short.MAX_VALUE)
      );

      jPMovimentar.setBorder(javax.swing.BorderFactory.createTitledBorder("Movimentar"));

      buttonGroup1.add(jRBAldeao);
      jRBAldeao.setSelected(true);
      jRBAldeao.setText("Aldeão");

      buttonGroup1.add(jRBArqueiro);
      jRBArqueiro.setText("Arqueiro");

      buttonGroup1.add(jRBCavaleiro);
      jRBCavaleiro.setText("Cavaleiro");

      buttonGroup1.add(jRBTodos);
      jRBTodos.setText("Todos");

      jBCima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cima.png"))); // NOI18N
      jBCima.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jBCimaActionPerformed(evt);
         }
      });

      jBEsquerda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/esquerda.png"))); // NOI18N
      jBEsquerda.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jBEsquerdaActionPerformed(evt);
         }
      });

      jBBaixo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/baixo.png"))); // NOI18N
      jBBaixo.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jBBaixoActionPerformed(evt);
         }
      });

      jBDireita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/direita.png"))); // NOI18N
      jBDireita.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jBDireitaActionPerformed(evt);
         }
      });

      jBCima1.setText("Atacar");
      jBCima1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jBCima1ActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPMovimentarLayout = new javax.swing.GroupLayout(jPMovimentar);
      jPMovimentar.setLayout(jPMovimentarLayout);
      jPMovimentarLayout.setHorizontalGroup(
         jPMovimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPMovimentarLayout.createSequentialGroup()
            .addGroup(jPMovimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addGroup(jPMovimentarLayout.createSequentialGroup()
                  .addContainerGap()
                  .addGroup(jPMovimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPMovimentarLayout.createSequentialGroup()
                        .addComponent(jRBAldeao)
                        .addGap(24, 24, 24)
                        .addComponent(jBCima1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                     .addComponent(jRBArqueiro)
                     .addComponent(jRBCavaleiro)
                     .addComponent(jRBTodos)))
               .addGroup(jPMovimentarLayout.createSequentialGroup()
                  .addGap(35, 35, 35)
                  .addGroup(jPMovimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(jBCima)
                     .addGroup(jPMovimentarLayout.createSequentialGroup()
                        .addComponent(jBEsquerda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBBaixo)))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jBDireita)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPMovimentarLayout.setVerticalGroup(
         jPMovimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPMovimentarLayout.createSequentialGroup()
            .addGroup(jPMovimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jBCima1, 0, 0, Short.MAX_VALUE)
               .addComponent(jRBAldeao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jRBArqueiro)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jRBCavaleiro)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jRBTodos)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPMovimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jBDireita)
               .addGroup(jPMovimentarLayout.createSequentialGroup()
                  .addComponent(jBCima)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPMovimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(jBEsquerda)
                     .addComponent(jBBaixo)))))
      );

      jPCriar.setBorder(javax.swing.BorderFactory.createTitledBorder("Criar"));

      jBAldeao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/aldeao.png"))); // NOI18N
      jBAldeao.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jBAldeaoActionPerformed(evt);
         }
      });

      jBCavaleiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cavaleiro.png"))); // NOI18N

      jBArqueiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arqueiro.png"))); // NOI18N

      javax.swing.GroupLayout jPCriarLayout = new javax.swing.GroupLayout(jPCriar);
      jPCriar.setLayout(jPCriarLayout);
      jPCriarLayout.setHorizontalGroup(
         jPCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPCriarLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jBAldeao)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jBCavaleiro)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jBArqueiro)
            .addContainerGap(17, Short.MAX_VALUE))
      );
      jPCriarLayout.setVerticalGroup(
         jPCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPCriarLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jBAldeao)
               .addComponent(jBCavaleiro)
               .addComponent(jBArqueiro))
            .addContainerGap(36, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout jPLateralLayout = new javax.swing.GroupLayout(jPLateral);
      jPLateral.setLayout(jPLateralLayout);
      jPLateralLayout.setHorizontalGroup(
         jPLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPLateralLayout.createSequentialGroup()
            .addGroup(jPLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPLateralLayout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(jPCriar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLateralLayout.createSequentialGroup()
                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jPMovimentar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
      );
      jPLateralLayout.setVerticalGroup(
         jPLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPLateralLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPCriar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jPMovimentar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jPTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addGroup(layout.createSequentialGroup()
            .addGap(12, 12, 12)
            .addComponent(jPLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void jBAldeaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAldeaoActionPerformed

      //obtendo o tamanho do JPanel TELA
      int largura = this.jPTela.getWidth();
      int altura = this.jPTela.getHeight();

      // criando o aldeao em um local aleatorio
      int x = this.sorteio.nextInt(largura - 50);
      int y = this.sorteio.nextInt(altura - 50);
      if (x < 0) { // garantindo que x não esteja fora do limite do JPanel
         x = 0;
      }
      if (y < 0) { // garantindo que x não esteja fora do limite do JPanel
         y = 0;
      }

      // invocando o método criarAldeao da classe Tela.
      // Foi necessário a coerção de tipos pois jPTela é do tipo JPanel.
      // Isso só foi possível pois Tela é uma subclasse de JPanel.
      ((Tela) this.jPTela).criarAldeao(x, y);

   }//GEN-LAST:event_jBAldeaoActionPerformed

   private void jBCimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCimaActionPerformed
      if (jRBAldeao.isSelected()) {
         ((Tela) this.jPTela).movimentarAldeao(0);
      }
   }//GEN-LAST:event_jBCimaActionPerformed

   private void jBBaixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBaixoActionPerformed
      if (jRBAldeao.isSelected()) {
         ((Tela) this.jPTela).movimentarAldeao(1);
      }
   }//GEN-LAST:event_jBBaixoActionPerformed

   private void jBEsquerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEsquerdaActionPerformed
      if (jRBAldeao.isSelected()) {
         ((Tela) this.jPTela).movimentarAldeao(2);
      }
   }//GEN-LAST:event_jBEsquerdaActionPerformed

   private void jBDireitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDireitaActionPerformed
      if (jRBAldeao.isSelected()) {
         ((Tela) this.jPTela).movimentarAldeao(3);
      }
   }//GEN-LAST:event_jBDireitaActionPerformed

   private void jBCima1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCima1ActionPerformed
      if (jRBAldeao.isSelected()) {
         ((Tela) this.jPTela).atacarAldeao();
      }
   }//GEN-LAST:event_jBCima1ActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      java.awt.EventQueue.invokeLater(new Runnable() {

         public void run() {
            new Principal().setVisible(true);
         }
      });
   }
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.ButtonGroup buttonGroup1;
   private javax.swing.JButton jBAldeao;
   private javax.swing.JButton jBArqueiro;
   private javax.swing.JButton jBBaixo;
   private javax.swing.JButton jBCavaleiro;
   private javax.swing.JButton jBCima;
   private javax.swing.JButton jBCima1;
   private javax.swing.JButton jBDireita;
   private javax.swing.JButton jBEsquerda;
   private javax.swing.JPanel jPCriar;
   private javax.swing.JPanel jPLateral;
   private javax.swing.JPanel jPMovimentar;
   private javax.swing.JPanel jPTela;
   private javax.swing.JRadioButton jRBAldeao;
   private javax.swing.JRadioButton jRBArqueiro;
   private javax.swing.JRadioButton jRBCavaleiro;
   private javax.swing.JRadioButton jRBTodos;
   // End of variables declaration//GEN-END:variables
}
